### ISSUE TITLE
ValueError: arrays have a total of 44851 colors...

### ISSUE THREAD

**Issue by nyck33** [WarrenWeckesser/numpngw#8]
```
ValueError: The arrays have a total of 44851 colors. With bit depth 8, no more than 256 colors are allowed when using a palette.
```
I have no idea what this means.  My code:
```
import cv2
import numpy
import numpngw

frames = []

count = 0

while True:
    if count < 10: 
        frame = cv2.imread("frame000"+str(count)+".png") 
        frames.append(frame) 
    elif count >=10: 
        frame = cv2.imread("frame00"+str(count)+".png") 
        if frame is None:
            break 
        else: 
            frames.append(frame) 
    count += 1

numpngw.write_apng('candle.png', frames, delay=50, use_palette=True)
```

**Comment by nyck33** [comment]
I was trying to make an infinitely looping gif of a burning candle from about 100 small .png images

**Comment by nyck33** [comment]
I did `use_palette=False` and it works.  When and where do we set this to True or False?  I saw your answer here and tried it:  https://stackoverflow.com/questions/753190/programmatically-generate-video-or-animated-gif-in-python

**Comment by WarrenWeckesser** [comment]
As the error message says, you can't use the argument `use_palette=True` if the image has more than 256 unique colors.  You can read more about PNG palettes here: http://www.libpng.org/pub/png/book/chapter08.html#png.ch08.div.5.  A palette is just a look-up table of colors.  When a palette is used, the image array stored in the PNG file is a two-dimensional array of integers in the range 0 to 255.  Each value is an index into the table of colors.  When a palette is not used, the image array is (in effect) an 3-d array, where the third dimension holds the RGB or RGBA values of the pixel.  With `write_png` or `write_apng`, you don't have to create the palette--the software creates it for you.

The `use_palette` option gives the user the *option* to use a palette in the PNG file, but it is never required.  You do not have to use a palette (and in your case, you can't, because you have more than 256 colors). 

Does that clear things up for you?

**Comment by nyck33** [comment]
Yes, thank you for taking your precious time to explain.
